name: 'trafficlens_dbt'
version: '1.0.0'
config-version: 2

profile: 'trafficlens_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  trafficlens_dbt:
    silver:
      +materialized: table
      +file_format: parquet
    gold:
      +materialized: table
      +file_format: parquet
